### ISSUE TITLE
Login Does't work anymore

### ISSUE THREAD

**Issue by arjunbazinga** [SkullTech/twitter-follow-bot#1]
I think the home page of twitter has changed, there is no activity upon running the script.

**Comment by skulltech** [comment]
@arjunbazinga Okay I will take a look at this. Thanks for the heads up.

**Comment by skulltech** [comment]
It is working for me. Can you check again if it's working? @arjunbazinga And sorry for following up on it after about 6 months xD.

**Comment by darkzbaron** [comment]
not working for me either getting the following error:

'''
[?] The filename of the csv: input.csv
Traceback (most recent call last):
  File "twitter-bot.py", line 70, in <module>
    main()
  File "twitter-bot.py", line 62, in main
    login(driver, settings)
  File "twitter-bot.py", line 23, in login
    driver.find_element_by_class_name('StreamsLogin').click()
  File "Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 488, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 858, in find_element
    'value': value})['value']
  File "Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"StreamsLogin"}
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16251 x86_64)

'''

**Comment by skulltech** [comment]
@darkzbaron @arjunbazinga Fixed.
